- debian/rules
Signed-off-by: Yurii Shestakov <yshestakov@gmail.com>
> debian/rules: added --with-iscsi-initiator

- debian/rules
- scripts/spdk.spec
Signed-off-by: Yurii Shestakov <yshestakov@gmail.com>
> Remove --enable-debug option

- debian/rules
- scripts/spdk.spec
Signed-off-by: Andrii Holovchenko <andriih@mellanox.com>
> Add --without-isal configure option

- scripts/spdk.spec
Signed-off-by: Yurii Shestakov <yshestakov@gmail.com>
> spdk.spec: Fixed check for RHEL-7.x distro

- scripts/build_rpm.sh
- scripts/spdk.spec
* put "Revision" value into the spec
* subst %{_sha1}, %{_branch} in the %changelog section
Signed-off-by: Yurii Shestakov <yshestakov@gmail.com>
> spdk.spec: make it MOFED builder friendly

- debian/control
- debian/rules
- debian/spdk-rpc.install
- debian/spdk.install
- scripts/setup.py
Signed-off-by: Yurii Shestakov <yuriis@mellanox.com>
> DEB: rework packaing of spdk-rpc

- debian/rules
Signed-off-by: Yurii Shestakov <yuriis@mellanox.com>
> DEB: Fixed packaging of spkd-rpc on Debian/Ubuntu

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8.2.2004
- .ci/Dockerfile.ubuntu20.04
- .ci/Jenkinsfile.shlib
- .ci/build_deb.sh
- .ci/build_rpm.sh
- .ci/job_matrix.yaml
- .ci/proj_jjb.yaml
- .ci/upload.sh
* Add files required to build spdk using ci-demo
> ci: integrate ci-demo

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8.2.2004
- .ci/Dockerfile.ubuntu20.04
- .ci/job_matrix.yaml
> ci: upgrade to mlnx_ofed 5.4

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8.2.2004
- .ci/Dockerfile.ubuntu20.04
- .ci/upload.sh
- debian/CONFIG
- debian/rules
added a new compilation option
> ci: added --with-xlio into configure

- .ci/Dockerfile.ubuntu20.04
> ci: added new ofed

- debian/rules
- scripts/spdk.spec
* Include spdk-gpt.py in rpm/deb packages
> pkg: add spdk-gpt.py

- .ci/job_matrix.yaml
> ci: use snap-ci k8s namespace

- .ci/Dockerfile.ubuntu20.04
- .ci/Dockerfile.ubuntu22.04
- .ci/job_matrix.yaml
- .ci/upload.sh
- debian/rules
> ci: added urm repo

- .ci/upload.sh
> ci: fixed rpc package

- contrib/setup_hugepages.sh
- contrib/spdk_tgt.service
> contrib: update setup_hugepages

- contrib/setup_hugepages.sh
* Check if Hugetlb > 0 and has enough size. Otherwise set it to MIN_HUGEMEM.
> contrib: setup_hugepages by Hugetlb

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8.2.2004
- .ci/Dockerfile.ubuntu20.04
- .ci/Dockerfile.ubuntu22.04
- .ci/job_matrix.yaml
> ci: update ofed 5.8-0.4.6.0

- contrib/spdk_tgt.service
* Add back setup_hugepages.sh as pre-start to systemd.
> contrib: add setup_hugepages to systemd

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8.2.2004
- .ci/Dockerfile.ubuntu20.04
- .ci/Dockerfile.ubuntu22.04
- .ci/job_matrix.yaml
Update ofed5.9 with new xlio-2.1.0
> ci: update ofed 5.9 on Ubuntu22

- .ci/Dockerfile.openeuler.20.03
- .ci/job_matrix.yaml
- .ci/upload.sh
- scripts/spdk.spec
> ci: add openEuleros 20.03 support

- .ci/upload.sh
> ci: fix new git behaviour in upload script

- .ci/Dockerfile.openeuler.20.03
> ci: disable default repos in openeuler

- .ci/Dockerfile.openeuler.20.03
- .ci/build_deb.sh
- .ci/build_rpm.sh
- scripts/spdk.spec
> ci: fix openeluer python3-pep8

- configure
Fix gas version check on rhel distributions.
> configure/misk: fix gas check on rhel

- configure
Fix gas version check on rhel distributions.
> configure/misc: fix gas check on rhel

- .ci/dpdk_patch.sh
- debian/CONFIG
- debian/control
- debian/rules
libxlio isn't supported in Debian, so restrict
this option only to Ubuntu.
> pkg: use --with-xlio only in Ubuntu

- module/sock/xlio/xlio.c
When we cannot handle all pending data, we must put a socket to the pending_recv to continue at the next polling cycle. Otherwise, the pending data is never polled.
The group_impl pointer checking is also fixed.
> sock/xlio: Fix error handling in xlio_sock_recv_zcopy()

- include/spdk_internal/sock.h
Value of sock request must be reset after the request is completed or aborted.
Change-Id: I149c2eb177ecedf5f835f13e0d0cdb2634058b87
> sock: Reset sock request after it's completed or aborted

- contrib/setup_vhost.py
- scripts/spdk.spec
> pkg: add ctyunos support

- .ci/Dockerfile.centos7.9.2009
> ci: changed openssl location

- .ci/Dockerfile.ubuntu22.04
- .ci/job_matrix.yaml
Switch to MLNX_OFED 24.04-0.1.7.0
> ci: MLNX_OFED 24.04-0.1.7.0

- .ci/job_matrix.yaml
> ci: MOFED 24.04-0.4.3.0

- .ci/Dockerfile.centos8
Fixes 'Could not resolve host: mirrorlist.centos.org'
> ci: fix centos yum url

- .ci/Dockerfile.openeuler.20.03
Fix 'short-name resolution enforced' error.
> ci: fix openeuler build

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8
- .ci/Dockerfile.openeuler.20.03
- .ci/Dockerfile.openeuler.22.03
- .ci/Dockerfile.rockylinux9.2
- .ci/job_matrix.yaml
- .ci/upload.sh
- scripts/spdk.spec
> ci: add openeuler 22.03 support

- .ci/Dockerfile.centos7.9.2009
- .ci/Dockerfile.centos8
- .ci/Dockerfile.debian12
- .ci/Dockerfile.openeuler.20.03
- .ci/Dockerfile.rockylinux9.2
- .ci/Dockerfile.ubuntu20.04
- .ci/Dockerfile.ubuntu22.04
- .ci/proj_jjb.yaml
- .ci/upload.sh
Changed URL for liburing1
Changed webrepo to nbu
> ci: fixed repos URL

- scripts/spdk.spec
> pkg: enable xlio for ctyunos

- .ci/proj_jjb_doca_nvmf_target_offload.yaml
> ci: update tgt offload git url
